import React, { useState, useEffect, useRef } from 'react';
import { Dashboard } from './components/Dashboard';
import { StudySession } from './components/StudySession';
import { Statistics } from './components/Statistics';
import { Achievements } from './components/Achievements';
import { Customization } from './components/Customization';
import { DifficultySelector } from './components/DifficultySelector';
import { ConfettiCelebration } from './components/ConfettiCelebration';
import { LevelUpCelebration } from './components/LevelUpCelebration';
import { ThemeProvider, useTheme } from './context/ThemeContext';
import { GameProvider, useGame } from './context/GameContext';
import { StatsProvider, useStats } from './context/StatsContext';